#!/bin/sh
if [ "$1" = "uninstall" ]; then
    brew remove avrdude
else
	if [ ! -f "/usr/local/bin/brew" ]; then
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi
    if [ ! -f "/usr/local/bin/avrdude" ]; then
        brew install avrdude
    fi
fi