#!/bin/sh

cd "$(dirname "$0")"

shopt -s nocasematch

checkUSB()
{
    for ((i = 0 ; i < 30 ; i++ )); do
        echo "... Waiting for USB"
        if [[ $i -eq 0 ]]; then
            openBrowser http://127.0.0.1:8080
        fi
        sleep 1
        return
    done
}

openBrowser()
{
    if [ -d /Applications/Firefox.app ]; then
        browser="Firefox"
    elif [ -d /Applications/Chrome.app ]; then
        browser="Chrome"
    else
        browser="Safari"
    fi

    open -a $browser $1 &
}

pkill -9 php
/usr/bin/php -S 0.0.0.0:8080 -t "$(dirname "$0")/Web/" &
sleep 2

checkUSB