#!/bin/sh

cd "$(dirname "$0")"

shopt -s nocasematch

openBrowser()
{
    if [ -d /Applications/Firefox.app ]; then
        browser="Firefox"
    elif [ -d /Applications/Chrome.app ]; then
        browser="Chrome"
    else
        browser="Safari"
    fi

    open -a $browser $1 &
}

./avrdude

pkill -9 php
/usr/bin/php -S 127.0.0.1:8080 -t "$(dirname "$0")/Web/" &
sleep 2

openBrowser http://127.0.0.1:8080